START TRANSACTION;

CREATE TABLE "InterviewProgress" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Category" character varying(50) NOT NULL,
    "QuestionId" character varying(50) NOT NULL,
    "ReadAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InterviewProgress" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterviewProgress_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_InterviewProgress_UserId_Category_QuestionId" ON "InterviewProgress" ("UserId", "Category", "QuestionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260808071319_AddInterviewProgress', '8.0.0');

COMMIT;

