START TRANSACTION;

CREATE TABLE "InterviewNotes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Category" character varying(50) NOT NULL,
    "QuestionId" character varying(50) NOT NULL,
    "NoteText" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InterviewNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InterviewNotes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_InterviewNotes_UserId_Category_QuestionId" ON "InterviewNotes" ("UserId", "Category", "QuestionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260808080148_AddInterviewNotes', '8.0.0');

COMMIT;

